### ISSUE TITLE
Develop subset of Sherlock code to match asteroid locations

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/rockAtlas#4]
Will need to return:

* separation from association 
* magnitude of matched association
* type of the source matched (star, galaxy, agn ...)

## TASKS

- [ ] plot a point-source magnitude distribution of SSObject detections found on top of catalogued point-source detections
- [ ] plot a delta-magnitude distribution of SSObject detections found on top of catalogued point-source detections (SSobject detection - point-source mag)
- [ ] write a sql function to convert sherlock classifications from 'ORPHAN' to 0, matched point sources brighter than 20th mag to 1 and matched point sources fainter than 20th mag to 0. I can then use this binary notation as a keep/reject indicator for SSObject detections.
